name: API deploy

on:
  release:
    types: [published]

jobs:
  api-doc-deploy:
    name: Deploy API doc on Bump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: icadsistemi/bump-action@v1
        with:
          doc: ${{ vars.BUMP_DOC_ID }}
          token: ${{ secrets.BUMP_TOKEN }}
          file: mxp-public-api-prod-oas30.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
