name: API build and deploy

on:
  push:
    paths:
      - mxp-public-api-prod-oas30.json
    branches:
      - master

jobs:
  api-doc-deploy:
    name: build doc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate new documentation
        run: |
          docker run --rm -v ${PWD}:/local swaggerapi/swagger-codegen-cli-v3 generate \
          -i local/mxp-public-api-prod-oas30.json \
          -l html2 \
          -o local/docs

      - name: Commit new documentation
        run: |
          git config --global user.name 'ICAD Sistemi'
          git config --global user.email 'action@icadsistemi.com'
          git add docs/
          git commit -am "update docs"
          git push
